insert into animal (nome, genero) values ('Lula', 'F');
insert into animal (nome, genero) values ('Damon', 'F');
insert into animal (nome, genero) values ('Ezequiel', 'M');
insert into animal (nome, genero) values ('Reeta', 'F');
insert into animal (nome) values ('Issiah');
insert into animal (nome) values ('Clarke');
insert into animal (nome, genero) values ('Alleyn', 'M');
insert into animal (nome) values ('Worthington');
insert into animal (nome, genero) values ('Diena', 'F');
insert into animal (nome) values ('Haily');
insert into animal (nome, genero) values ('Rene', 'F');
insert into animal (nome, genero) values ('Matthaeus', 'F');
insert into animal (nome) values ('Sidonnie');
insert into animal (nome) values ('Bourke');
insert into animal (nome) values ('Lorri');
insert into animal (nome, genero) values ('Jocelyn', 'F');
insert into animal (nome) values ('Cindee');
insert into animal (nome, genero) values ('Abra', 'F');
insert into animal (nome, genero) values ('Catherine', 'F');
insert into animal (nome, genero) values ('Nat', 'F');
