insert into carro (fabricante, modelo, preco) values ('Lamborghini', 'Diablo', 89781.01);
insert into carro (fabricante, modelo, preco) values ('GMC', 'Safari', 72854.88);
insert into carro (fabricante, modelo, preco) values ('Mercedes-Benz', 'CL-Class', 66317.26);
insert into carro (fabricante, modelo, preco) values ('Eagle', 'Vision', 57987.14);
insert into carro (fabricante, modelo, preco) values ('Mazda', 'MX-5', 37658.0);
insert into carro (fabricante, modelo, preco) values ('Honda', 'Civic', 78376.49);
insert into carro (fabricante, modelo, preco) values ('Jaguar', 'S-Type', 18005.24);
insert into carro (fabricante, modelo, preco) values ('Audi', 'Quattro', 82920.55);
insert into carro (fabricante, modelo, preco) values ('Suzuki', 'Equator', 83452.72);
insert into carro (fabricante, modelo, preco) values ('Ford', 'Escape', 62621.21);
insert into carro (fabricante, modelo, preco) values ('Ram', '2500', 13522.85);
insert into carro (fabricante, modelo, preco) values ('Isuzu', 'Stylus', 80254.16);
insert into carro (fabricante, modelo, preco) values ('Ford', 'F-Series', 32450.21);
insert into carro (fabricante, modelo, preco) values ('Nissan', 'Sentra', 60047.27);
insert into carro (fabricante, modelo, preco) values ('GMC', 'Jimmy', 75361.44);
insert into carro (fabricante, modelo, preco) values ('Mercury', 'Grand Marquis', 28479.25);
insert into carro (fabricante, modelo, preco) values ('Chevrolet', 'G-Series G20', 70158.33);
insert into carro (fabricante, modelo, preco) values ('Saturn', 'VUE', 76610.46);
insert into carro (fabricante, modelo, preco) values ('Subaru', 'Forester', 31910.76);
insert into carro (fabricante, modelo, preco) values ('Dodge', 'D250', 44363.0);
insert into carro (fabricante, modelo, preco) values ('Mazda', 'CX-7', 86454.13);
insert into carro (fabricante, modelo, preco) values ('Lexus', 'GS', 19743.4);
insert into carro (fabricante, modelo, preco) values ('Hummer', 'H2', 62526.77);
insert into carro (fabricante, modelo, preco) values ('Mercedes-Benz', 'G-Class', 28322.4);
insert into carro (fabricante, modelo, preco) values ('GMC', 'Sierra 2500', 31328.16);
insert into carro (fabricante, modelo, preco) values ('BMW', 'Z3', 58723.09);
insert into carro (fabricante, modelo, preco) values ('Volvo', 'XC90', 87307.29);
insert into carro (fabricante, modelo, preco) values ('Dodge', 'Intrepid', 18000.4);
insert into carro (fabricante, modelo, preco) values ('Toyota', 'Land Cruiser', 73323.15);
insert into carro (fabricante, modelo, preco) values ('Chevrolet', 'Silverado 3500', 14515.66);
